version: '3'

services:

  page_analyzer:
    build: .
    restart: always
    ports:
      - '8080:8000'
    depends_on:
      - postgres
    command: make start
    env_file:
      - compose/env/page_analyzer.env

  postgres:
    image: postgres:16.6
    restart: always
    env_file:
      - compose/env/postgres.env
    volumes:
      - ./compose/init_db:/docker-entrypoint-initdb.d
